# Site settings
title: manukall
header-img: img/fox.jpg
email: mk@manukall.de
description: "Software development with Ruby, Rails, Elixir, Javascript and more."
baseurl: ""
url: "http://mk@manukall.de"
twitter_username: manukall
github_username:  manukall

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
