# Site settings
title: manukall
header-img: img/fox.jpe
email: mk@manukall.de
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://mk@manukall.de"
twitter_username: manukall
github_username:  manukall

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
